### ISSUE TITLE
 Oscillator calibration sketch does not compile

### ISSUE THREAD

**Issue by Win-doze** [MCUdude/MicroCore#97]
Firstly apologies if I am being incompetent, I am trying to compile the Oscillator calibration sketch but it fails to compile using Arduino 1.18.10. The first error I get is "'TXDELAYCOUNT' was not declared in this scope". If I declare TXDELAYCOUNT then I get further errors of undeclared variables and the Serial functions. I can only assume these are declared elsewhere and I am failing to pick up the headers or declarations somehow. Any pointers to sorting this out would be appreciated - Thanks.

**Comment by Win-doze** [comment]
I think I have solved the issue, I searched my Mac for the microcore files but could not find them even though the Arduino environment said I had the latest version loaded. I removed the core using boardmanager then manually installed MicroCore into the /documents/arduino/hardware folder. Then the file compiled without errors! I have no idea why the automatic installation failed to load the files but reported them installed.
